@isTest
private class BT_DummyCode3Test {

    private static testMethod void test() {
        BT_DummyCode3.codeCoverage();
        BT_DummyCode3.codeCoverage2();
        BT_DummyCode3.codeCoverage3();
        BT_DummyCode3.codeCoverage4();
        BT_DummyCode3.codeCoverage5();
        BT_DummyCode3.codeCoverage6();
        BT_DummyCode3.codeCoverage7();
        System.assertEquals('Test','Test');
    }

}