public class getMSAEmailData {

    
/*public List<buildertek__MSA_Settings__c> msaData {get; set;}
public string AccountID {get; set;}
public getMSAEmailData(){
    system.debug(AccountID+'AccountID');
    msaData = [select id,
               buildertek__Pre_Qual_Body__c,buildertek__Pre_Qual_Link_Helptext__c,buildertek__Pre_Qual_Template__c 
               from buildertek__MSA_Settings__c];
 }*/
}