@isTest
public class QuoteFooterEdit_TC {
    /*static TestMethod void quoteController(){
    	
      buildertek__Template_Footer__c  th = new buildertek__Template_Footer__c ();
      th.buildertek__Description__c = 'Test description for template header';
      th.buildertek__Template_Footer__c = 'Test';
      insert th;
      
      ApexPages.currentPage().getParameters().put('retURL', th.id); 
      
      ApexPages.StandardController sc = new ApexPages.StandardController(th);
      QuoteFooterEdit_AC  qh = new  QuoteFooterEdit_AC(sc);
      
      
      qh.isError = true;
      qh.verifyError();
      qh.Save(); 
      qh.CancelQuoteFooter();
      system.assertEquals(th.id,th.id);
    }
    
     static TestMethod void quoteController1(){
    	
      buildertek__Template_Footer__c  th2 = new buildertek__Template_Footer__c ();
      th2.buildertek__Description__c = 'Test1 description for template header';
      th2.buildertek__Template_Footer__c = '';
      insert th2;
      
      ApexPages.currentPage().getParameters().put('retURL', th2.id); 
      
      ApexPages.StandardController sc = new ApexPages.StandardController(th2);
      QuoteFooterEdit_AC  qh = new  QuoteFooterEdit_AC(sc);
      qh.isError = true;
      qh.verifyError();
      qh.Save(); 
      qh.CancelQuoteFooter();
      system.assertEquals(th2.id,th2.id);
    }
   */
}